import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import LayoutWrapper from "@/components/LayoutWrapper"; // Import client wrapper
import { Toaster } from "@/components/ui/toaster"
import { Nunito_Sans } from "next/font/google";

const nunitoSans = Nunito_Sans({ 
  weight: ["300", "400", "500", "600", "700", "800"], 
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      
      <body className={nunitoSans.className}>
        <SidebarProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
          <Toaster />
        </SidebarProvider>
      </body>
    </html>
  );
}
