name: Build and Deploy to Docker Hub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Ensure the path to Dockerfile is correct
          push: true
          tags: aayushsharma100/simplylearnweb:latest
          build-args: |
            NEXT_PUBLIC_BASE_URL=https://apisimplylearn.selflearnai.in/api/v1
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GOOGLE_AI_API_KEY=${{ secrets.GOOGLE_AI_API_KEY }}

      - name: Verify Pushed Image
        run: docker pull aayushsharma100/simplylearnweb:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker image prune -f
            sudo docker pull aayushsharma100/simplylearnweb:latest
            sudo docker stop simplylearnweb || true
            sudo docker rm simplylearnweb || true
            sudo docker run -d --name simplylearnweb --restart always -p 3000:3000 \
              -e NEXT_PUBLIC_BASE_URL=https://apisimplylearn.selflearnai.in/api/v1 \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              -e GOOGLE_AI_API_KEY=${{ secrets.GOOGLE_AI_API_KEY }} \ 
              aayushsharma100/simplylearnweb:latest
